name: Run Selenium Cucumber Tests in Docker

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t selenium-tests .

      - name: Run Selenium Cucumber Tests in Docker
        run: docker run --rm selenium-tests
