name: Run Selenium Cucumber Tests in Docker

on:
  workflow_dispatch:
    inputs:
      test_env:
        description: 'Test Environment (e.g., staging, production)'
        required: false
        default: 'qa'
      cucumber_tags:
        description: 'Tags to Run'
        required: false
        default: '@login'
  push:
    branches:
      - java_selenium
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t selenium-tests .

      - name: Run Selenium Cucumber Tests in Docker
        run: docker run --rm selenium-tests
