name: Run Selenium Cucumber Tests in Docker

on:
  workflow_dispatch:
    inputs:
      test_env:
        description: 'Test Environment (e.g., staging, production)'
        required: false
        default: 'qa'
      cucumber_tags:
        description: 'Tags to Run'
        required: false
        default: '@login'
  push:
    branches:
      - java_selenium
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t selenium-tests .

      - name: Run Selenium Cucumber Tests in Docker
        run: docker run --rm selenium-tests/test-reports:/app/test-reports selenium-tests

      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline
          allure generate allure-results --clean -o test-results/allure-report || echo "Allure report generation failed."
          ls -la test-results/allure-report 
          # mkdir -p allure-report/history
          # if [ -d allure-report ]; then cp -r allure-report/history test-results/allure-results/; fi
          # npm install -g allure-commandline
          # allure generate allure-results --clean -o allure-report

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: test-reports/
         
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: test-results/allure-report 

      - name: Debug Playwright Report
        run: ls -la test-results/playwright-report || echo "No Playwright report found"

      # - name: Upload Playwright Test Results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: playwright-html-report
      #     path: playwright-report/
      #     if-no-files-found: ignore  # ✅ Ignore missing files instead of showing warnings

      - name: Deploy Allure Report to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PATJ }}
          publish_branch: gh-pages
          publish_dir: test-results/allure-report 
          destination_dir: allure-report
          keep_files: false
          
      # - name: Deploy Playwright HTML Report to GitHub Pages
      #   if: success()
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     personal_token: ${{ secrets.GH_PATJ }}
      #     publish_branch: gh-pages
      #     publish_dir: playwright-report/
      #     destination_dir: playwright-report
      #     keep_files: false
